language: python
sudo: false
python:
- 3.3
- 3.4
- 3.5
- pypy3
matrix:
 allow_failures:
 - python: pypy3
env:
  global:
  # GitHub
  - secure: "jZVzNDRii4P1ay6FIlzMbuIVE2u4o4trSwWD09G0MVLv1PLbv05a4ToDjwYv7b8hcOeTIUAUHtTNaaIwuPf256OUhpmRoROy/XkdShZGh5pw4RrTH2Pgo3hxjRN011AzcUmVoiw68hYHSN9yzVZHhtVrKKwXP2H96Aae6BTmCPA="
  # S3
  - secure: "F8AKUR2WrOt2POoFL4I1h2KEvffYGc+RgjzYnmLUNsFCfsL+tZSa3enxCPJQs7UZLr23PIhKDiPgASGscQJbH7yiqQ5EHnrdiPQVAphj7qtrKHJkqGy3UeSsrOI/PhWTO0fmE0bs+9BWl86Lg+M5R0oLHdapOOFhu+pwXyoC8rc="
  - secure: "GTRvF2s/RcnmUINh6LlHGBZedDP8KyaD15u/Cy4fgq+9pqqbhGNCcBlrlvpw/Vlf1iDLqG9nm5LRFLcbv6SmdEeucU2vQlC9g2c4MZJGEq+yMMbG/LKnpGGSXH08zMIAzk4hjNWGXRdT3N5HswLAnc2YlHj6tk2Y5dlufgQGEJw="
services:
- redis-server
install:
- pip install --upgrade setuptools pip
- pip install -f https://github.com/spoqa/sftpserver/releases sftpserver==0.2setuptools  # FIXME
- pip install -e .[tests]
- pip install psycopg2 PyMySQL http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.4.zip
- pip install pytest-cov codecov flake8
before_script:
- createdb -U postgres -E utf8 -T postgres geofront_test
- mysql -e 'CREATE DATABASE geofront_test;'
script:
- python -mgeofront.version
- REDIS_HOST=localhost PGDATABASE=geofront_test PGUSER=postgres MYSQL_DATABASE=geofront_test MYSQL_HOST=localhost MYSQL_USER=root py.test -vv --cov geofront --durations=20 --sshd-state-timeout=60
- flake8
after_success:
- codecov
